### ISSUE TITLE
colour of buttons a little brighter

### ISSUE THREAD

**Issue by omega3** [krassowski/Anki-Night-Mode#10]
May they be a little brighter - to distinguish them from surrounding background?
I am not sure if this is the effect of night mode colour or my KDE theme (Breeze dark).
http://i.imgur.com/hu843bX.jpg

By the way: do you happen to know if it is possible to use this add-on 
Bigger Show All Answer Buttons
https://ankiweb.net/shared/info/2034935033
to make edit buttons bigger? Perhaps both things could be done by separate add-on or just by editing night mode and Bigger Show All Answer Buttons?

**Comment by krassowski** [comment]
The first one is fixed in new version of add-on along with Anki version 2.1, see: http://imgur.com/a/2BNao. To get this working, install Anki 2.1 alpha11 and newest version of add-on from repository, from master branch.
