### ISSUE TITLE
Leaving and coming back to a profile leads to an error message

### ISSUE THREAD

**Issue by Arthur-Milchior** [krassowski/Anki-Night-Mode#102]
#### Problem description

There is an error message when I leave my profile and come back to the same or to another profile.
(I tested with 19 and beta 20)

#### Checklist

*Please put x inside brackets if following sentences apply to you:*

 - [x] I verified that I use the lastest add-on version,
 - [x] I verified that I use the lastest Anki version, (I tested with 19 and beta 20)
 - [x] I tried to disable other add-ons to find the culprit,
 - [x] I checked if anyone reported this problem before, as well as Known issues section on add-ons page,
 - [x] My issue is solved when holding shift while starting Anki.
 
#### Information about your Anki Setup

<details>

```
Version 2.1.20 (95b497cc)
Python 3.8.1 Qt 5.14.0 PyQt 5.13.2
```

*Please got to Night Mode → About now and copy-paste the first line from the pop-up window below:*

```
Night Mode 2.3.1
```

*Please fill in your OS details (Linux/Mac/Windows):*

```
OS: Ubuntu (latest version)
```
 
 
*If you have a compatibility problem with a specific add-on or add-ons, please paste the add-on page links below:*
 - [Other add-on name](https://)
</details>

#### Backtrace (if any)

```python"
Caught exception:
Traceback (most recent call last):
  File "aqt/progress.py", line 73, in handler
  File "/home/arthur/.local/share/Anki2/addons21/1496166067/__init__.py", line 11, in delayedLoader
    night_mode = NightMode()
  File "/home/arthur/.local/share/Anki2/addons21/1496166067/night_mode.py", line 131, in __init__
    self.menu = Menu(
  File "/home/arthur/.local/share/Anki2/addons21/1496166067/menu.py", line 55, in __init__
    self.create_action(
  File "/home/arthur/.local/share/Anki2/addons21/1496166067/menu.py", line 75, in create_action
    raise Exception(message)
Exception: Action enable_night_mode already exists
```

</details>

**Comment by lovac42** [comment]
That was my boo boo... See #99

**Comment by Arthur-Milchior** [comment]
"your boo boo" ? I don't get it.
Yeah, I didn't really take a look at PR, only at Bug Reports to see if it was a duplicate or not

**Comment by lovac42** [comment]
"A minor oversight".

It's fine, leave this ticket open so it won't get reposted.
