### ISSUE TITLE
Compatibility issues with Image Style Editor

### ISSUE THREAD

**Issue by BlueGreenMagick** [krassowski/Anki-Night-Mode#104]
#### Problem description
EDIT: See next post for why this bug occured.
As title says, the latest update broke compatibility with my addon Image Style Editor. I've tried to figure out what was going on, but I still have no idea and I'm hoping that you will fare better than me.

I put tooltip functions at various points in my addon and It seemed that onProfileLoaded function was not being called. So I commented out this [line](https://github.com/krassowski/Anki-Night-Mode/blob/master/night_mode/__init__.py#L15)(which calls remHook) and it fixed the issue, which led me to think that somehow remHook was removing hook from my addon.

And so I renamed my function to onProfileLoaded22 and ran the following code in anki's debug window: 
```
from anki.hooks import _hooks
print(_hooks["profileLoaded"])
```
And to my surprise, onProfileLoaded22 function was still in _hooks. And yet it was not being called.

[remHook](https://github.com/ankitects/anki/blob/2.1.19/pylib/anki/hooks.py#L57) is defined this way:
```
def remHook(hook, func) -> None:
    hook = _hooks.get(hook, [])
    if func in hook:
        hook.remove(func)
````

So I still have absolutely no idea what is happening.

#### Checklist

*Please put x inside brackets if following sentences apply to you:*

 - [x] I verified that I use the lastest add-on version,
 - [x] I verified that I use the lastest Anki version,
 - [ ] I tried to disable other add-ons to find the culprit,
 - [x] I checked if anyone reported this problem before, as well as Known issues section on add-ons page,
 - [ ] My issue is solved when holding shift while starting Anki.
 
#### Information about your Anki Setup

<details>

*Please open Anki, go to Help → About, look-up two lines, starting with `Version:` and `Qt` and copy-paste them below:*

```
Version: 2.1.19 (3c8690ae)
Python 3.8.1 Qt 5.14.0 PyQt 5.13.2
```

```
Night Mode 2.3.2
```

```
OS: Linux Mint 19.3
```
 
 - [Image Style Editor](https://ankiweb.net/shared/info/1593969147)
</details>

**Comment by BlueGreenMagick** [comment]
Finally figured out what was going wrong!

Say NightMode's hook function was at index 0. When Anki runHook, hook[0] is ran first in for loop, which would be NightMode's. When you call remHook in the same hook function, the function is removed from hook. So the next function which was hook[1] becomes hook[0]. Then Anki executes the next function attached to hook, hook[1]. Which causes hook[0](previously hook[1]) to not get executed. Image Style Editor's hook function must have been right after Night Mode's.

This should be fixed if you did not remove hook while in the same hook's function.

**Comment by lovac42** [comment]
Yeah see #103, Switching profile and returning profile also works.
I'll make a PR to fix this later, sorry for the inconvenience.
