### ISSUE TITLE
Latest NightMode Broke ReMemorize Addon

### ISSUE THREAD

**Issue by mackiechan3** [krassowski/Anki-Night-Mode#106]
#### Problem description

The "ReMemorize: Rescheduler with sibling and logging (v1.2.1)" addon no longer works for me, and I've isolated the problem to NightMode. (The ReMemorize addon affects changing intervals, rescheduling cards, changing due date, etc.) These functions no longer work when NightMode is enabled. I get no error messages, pop ups or anything, ReMemorize just doesn't funtion - as though the addon doesn't exist. And when I disable only NightMode, Rememorize starts working again. 

#### Checklist

*Please put x inside brackets if following sentences apply to you:*

 - [x] I verified that I use the lastest add-on version,
 - [x] I verified that I use the lastest Anki version,
 - [x] I tried to disable other add-ons to find the culprit,
 - [x] I checked if anyone reported this problem before, as well as Known issues section on add-ons page,
 - [] My issue is solved when holding shift while starting Anki.
 
#### Information about your Anki Setup

Sorry bro, the rest is way too much for me to fill out lmao, I don't wanna spend 30min just reporting an error. I had to make a github account and everything already just to report this issue.  I have the latest anki 2.1.19, latest macOS, and this problem just started with the last nightmode update, which was like on 1/25 or 1/26. If this isnt enough info already to address the issue don't sweat it, sorry I don't have more time to fill it all out.

**Comment by lovac42** [comment]
Thanks for reporting, see #103, #104, #105
A fix should be rolled out soon, sorry for the inconvenience.

There is also a new version of ReMemorize v1.3 if you want to test it.
https://github.com/lovac42/ReMemorize/releases
