### ISSUE TITLE
Night mode doesn't work with Anki 2.1.26

### ISSUE THREAD

**Issue by DSisss** [krassowski/Anki-Night-Mode#113]
#### Problem description

Night mode doesn't work with the latest updated version of Anki 2.1.26, saying 'Invalid code, or add-on not available for your version of Anki', when trying to redownload it.

#### Checklist

*Please put x inside brackets if following sentences apply to you:*

 - [x] I verified that I use the lastest add-on version,
 - [x] I verified that I use the lastest Anki version,
 - [x] I tried to disable other add-ons to find the culprit,
 - [x] I checked if anyone reported this problem before, as well as Known issues section on add-ons page,
 - [ ] My issue is solved when holding shift while starting Anki.
 
#### Information about your Anki Setup

<details>

*Please open Anki, go to Help → About, look-up two lines, starting with `Version:` and `Qt` and copy-paste them below:*

```
Version 2.1.26 (70784154)
Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
```

*Please got to Night Mode → About now and copy-paste the first line from the pop-up window below:*

```
Night Mode 2.1.19
```

*Please fill in your OS details (Linux/Mac/Windows):*

```
OS: Windows
```
 
 
*If you have a compatibility problem with a specific add-on or add-ons, please paste the add-on page links below:*
 - [Other add-on name](https://)
</details>

#### Backtrace (if any)

<details>

*If you had an error which resulted in producing exception with a backtrace, please paste the backtrace below:*

</details>

**Comment by krassowski** [comment]
Yes, it is intended as the newer versions have built-in night mode.
