### ISSUE TITLE
chinese  bug

### ISSUE THREAD

**Issue by liudaozhenjun** [krassowski/Anki-Night-Mode#17]
when i input chinese,the first line has no problem,but the second and after lines auto change to black color,whick lead to the font color same as background color,when i unfocus the input ,it goes well .
![a7577292-f31a-4162-91e9-00e49c56eaaa](https://cloud.githubusercontent.com/assets/20336673/24634519/ecd6ccea-1900-11e7-9703-373875a3fef8.png)

**Comment by JunjieLi91** [comment]
I've met the same question on win7 ,but it run normally on win10.

**Comment by krassowski** [comment]
Could you test this with Anki 2.1?

**Comment by krassowski** [comment]
I found some bug reports about Chinese input changing text color in Qt (this is the framework used by Anki for displaying windows and most of the content).

- [QWebView text color changed when i input string using input method](https://bugreports.qt.io/browse/QTBUG-49074)
- [qwebpage font color had changed when input chinese when setContentEditable(true)](https://bugreports.qt.io/browse/QTBUG-49074)

Newer versions of PyQt (5.9+) might have resolved this problem.

**Comment by krassowski** [comment]
Closing as, I received confirmation that for 2.1.6 and newest Anki 2.1 the problems are gone.
