### ISSUE TITLE
Text over difficulty buttons is hard to read

### ISSUE THREAD

**Issue by freddydumont** [krassowski/Anki-Night-Mode#19]
See image below:
<img width="209" alt="difficulty buttons" src="https://user-images.githubusercontent.com/15388588/27876134-f1e8ebe8-6183-11e7-84ca-a157a914b8b9.png">

Shouldn't this be the same color as the card text?

**Comment by krassowski** [comment]
Yes, it should. It's definitely a regression bug. Should be easy to fix with one or two CSS rules. PR welcome :)

**Comment by mjstew33** [comment]
i'm having the same issue. I've tried hard looking at the CSS but i can't figure it out. help please?

**Comment by krassowski** [comment]
I updated the add-on and it should work after re-installing the add-on.
Please let me know if it works for you.

**Comment by mjstew33** [comment]
Awesome I'm using it again immediately. Thanks a ton.

Sent from my iPhone
________________________________
