### ISSUE TITLE
Night Mode and "Special" text

### ISSUE THREAD

**Issue by gistgist** [krassowski/Anki-Night-Mode#2]
In night mode it's very difficult to read "special" decks or annoucements (i.e. custom study sessions or the message anki gives about too many decks).
Is there a way to change the color of this text (either via Anki settings or night mode)?

Image attached, see deck titles on lefthand side
<img width="507" alt="screen shot 2015-10-27 at 2 33 54 pm" src="https://cloud.githubusercontent.com/assets/15349336/10770166/ceedc40e-7cb7-11e5-8327-e16c0440de1b.png">

**Comment by krassowski** [comment]
Will work on that during this weekend ;)

**Comment by krassowski** [comment]
Ok, @gistgist this annoying behavior should be gone :) Please, give me a feedback if it works fine after updating the add-on to new version.

**Comment by gistgist** [comment]
Thank you! The update looks great.
For future updates, does Anki have a quick way to update addons (all or individually)?

**Comment by krassowski** [comment]
I haven't heard of any yet :( Some add-ons implements automatic updates, but I'm not sure if this should be a part of this add-on - I will think how to make upgrading process easier. Thanks for your report and feedabck.
