### ISSUE TITLE
Automatic Night Mode

### ISSUE THREAD

**Issue by p2635** [krassowski/Anki-Night-Mode#22]
I've just downloaded this add-on, well done!

Would be great if you could set it to only turn on/off during specific times.

**Comment by krassowski** [comment]
I like the idea. I welcome pull requests. I plan to spend some time re-factoring the add-on this or next weekend. If there is no news from me feel free to ping me there to remind me about this issue. Thanks!

**Comment by krassowski** [comment]
This has been implemented for 2.1.x. I will be happy to hear your feedback!

**Comment by p2635** [comment]
That was quick! Do I have to reinstall it to see?

**Comment by krassowski** [comment]
Yes. And it will only work with Anki 2.1 (currently beta 16)

**Comment by krassowski** [comment]
I just fixed a bug which caused some time intervals (which included midnight) to be interpreted incorrectly. Please make sure that you use the latest version. Enjoy!
