### ISSUE TITLE
Keep the original colors of the card

### ISSUE THREAD

**Issue by gitzen0** [krassowski/Anki-Night-Mode#25]
While it's not much of an issue, my cards styling already uses dark colors and I would like to know if there is a way to prevent the add-on changing the colors only for the card body, while preserving its functionality for everything else.
I guess I have to change something in the config but I'm just about to start learning Python, so I don't really know what to do. Thanks for the great add-on by the way!

**Comment by krassowski** [comment]
You could try to remove lines [187-190 from `stylers.py`](https://github.com/krassowski/Anki-Night-Mode/blob/master/night_mode/stylers.py#L187) file. Please let me know if it worked.

**Comment by gitzen0** [comment]
Oh, I've noticed I'm using the 1.2.3 version of the add-on and newer versions are only supported by Anki 2.1.x. But I was curious and I installed Anki beta in a sandbox and checked your solution. Nothing really happens, the colors are still inverted. 
Never mind, I'll wait until other add-ons support the 2.1.x version and after that I'll try to find a solution. For now I'll use the add-on as it is.

**Comment by krassowski** [comment]
Implemented in 2.1.5; to achieve such effect, go to the menu "View >> Night Mode >> Choose what to style" and disable "Reviewer" and "Anki Web View".
