### ISSUE TITLE
Black text/icons in Browser

### ISSUE THREAD

**Issue by nathanmalloy** [krassowski/Anki-Night-Mode#28]
All of the icons in the left panel of the browser dialog are hard to see. The black text on the purple background happens when I click on the Current Deck item, then click on a card in the card list.

![image](https://user-images.githubusercontent.com/7686246/33522288-5e602974-d7a6-11e7-8050-58eff536602c.png)

Using Windows Anki Version 2.1.0beta26
Qt 5.9.2 PyQt 5.9
Night Mode 2.1.2

**Comment by krassowski** [comment]
Thanks for your report. I am afraid that I cannot help with the black icons for now, but I've tried to make the selected field always have a bright color. As I could not reproduce your problem on my Linux machine, could you try to install the newest version from GitHub (remove add-on, download [this zip file](https://github.com/krassowski/Anki-Night-Mode/archive/master.zip), unpack and copy `night_mode` directory to your addons dir) and let me know if it worked?
You can find the add-ons directory going into Tools -> addons, clicking on "show files" of any of addons and the navigating one directory up.

**Comment by nathanmalloy** [comment]
The fix is working for the items in the left panel, but I'm seeing the same issue for the card list.
