### ISSUE TITLE
Nightmode anki 2.1 beta 31

### ISSUE THREAD

**Issue by gk12321** [krassowski/Anki-Night-Mode#30]
i updated my anki to beta 31, unfortunately it isnt working for beta 31, i use anki a lot and nightmode was very important to me, because i felt less tired when i had it on. 

i was wondering if you could get the update working for beta 31. as a student it would be so so so helpful.

**Comment by krassowski** [comment]
Thank you for pointing this out. I uploaded a new version to ankiweb. The standard procedure of remove/install again should make it possible for you to use the latest beta in night mode again.

Please let me know if everything works for you after updating the add-on.
