### ISSUE TITLE
Action buttons don't fit on GUI correctly when Night Mode is enabled

### ISSUE THREAD

**Issue by dastefster** [krassowski/Anki-Night-Mode#33]
I'll start off by saying I'm both new to using add-ons _and_ to Anki as a whole, so this issue may very well be the result of something I've done wrong, incorrect settings, etc. If so, I apologize in advance!

After installing the add-on and re-launching Anki, I activated Night Mode without changing any of its  settings. I immediately noticed the text was a litter larger than the default view, which is fine, but it also causes the action buttons (i.e., _'Get Shared'_, _'Create Deck'_, & _'Import File'_) at the bottom of the deck list to appear halfway pushed off the bottom edge of the GUI (see pics below). 
### screenshot right before enabling Night Mode:
![default](https://user-images.githubusercontent.com/10735136/37445869-52685320-27e8-11e8-837b-d8d9a9408cfb.png)
### You can see the buttons are no longer positioned correctly in the window:
![night_mode_enabled](https://user-images.githubusercontent.com/10735136/37445870-52784be0-27e8-11e8-86ed-e7883eab52ef.png)

**Any thoughts on what could be causing this?** 

_note: I am using Anki Version 2.0.50 on a MBP running macOS 10.13.3_

**Comment by krassowski** [comment]
Apologies that I did not find time respond to this issue. As I no longer support Anki 2.0 I will close this issue for now. Please, feel free to create a new issue if the problem persists in Anki 2.1
