### ISSUE TITLE
scrollbar colour

### ISSUE THREAD

**Issue by omega3** [krassowski/Anki-Night-Mode#35]
Because of the issue with QtWebKit I need to use 2.0.50 binary build
https://anki.tenderapp.com/discussions/ankidesktop/27629-no-module-named-qtwebkit-anki-2050

The problem is that it ignores system style settings and scrollbars on the right (both in study mode and in browser mode) when I use nightmode add-on are barely visible. They have the same dark color as the whole dark background. 

Also on the left in browser mode where the field where decks and tags are listed is blue and has white font which makes it hardly readable.

Is it possible to code an option for these two elements to change color in nightmode add-on?

**Comment by krassowski** [comment]
It should be possible; could you provide some screenshots?

PS. Personally, I would go with Anki 2.1 Beta. No one wants to support QT4 any longer.

**Comment by omega3** [comment]
https://imgur.com/a/wvHE5

Anki 2.1 doesn't support yet all add-on that I use.

**Comment by krassowski** [comment]
I could not reproduce your issue:

![screenshot from 2018-04-12 12-54-47](https://user-images.githubusercontent.com/5832902/38673230-06190a44-3e51-11e8-85fb-4ae2dbd99fe8.png)
![screenshot from 2018-04-12 12-55-26](https://user-images.githubusercontent.com/5832902/38673233-0a6f5800-3e51-11e8-9070-f37167d11680.png)
![screenshot from 2018-04-12 12-58-07](https://user-images.githubusercontent.com/5832902/38673317-417188e6-3e51-11e8-80b7-4e62e9d16550.png)
![screenshot from 2018-04-12 12-58-37](https://user-images.githubusercontent.com/5832902/38673321-44bbeb2c-3e51-11e8-810c-ad5ff82af0d3.png)

Which version of the add-on do you use?

**Comment by omega3** [comment]
Any chances for this feature in the near future? Being unable to use Anki 2.1 that are in repositories in Ubuntu 18.04 (because of lack of important add-ons) I am forced to stay on old Ubuntu version because of Anki. With lots of editing and work on my database the visibility of scrollbar is an important feature for me. The alternative is to use light desktop theme for the whole desktop but hmm - if I preferred light themes I wouldn't need night mode add-on. 

Waiting for all important add-on that I use - to be able to switch to anki 2.1 - make take another year...

**Comment by krassowski** [comment]
In the fresh 2.1.8 for Anki 2.1 there is an option to enable neat, tailored, dark scrollbars styling. Although I do not plan back-porting this feature to the old version (as Anki 2.1 has just been officially released), one could easily copy-paste the relevant CSS code into the old version.

**Comment by omega3** [comment]
In 2.1 it works great. But I really have no idea what and where to paste in 2.0. 
I have no knowledge of python. 
I only discrovered that important part is in file style in 2.1.

Can you please explain or just paste on pastebin site the code for 2.0 (without changing anything on Anki 2.0 add-ons site)?
