### ISSUE TITLE
crash if sync after open browser

### ISSUE THREAD

**Issue by ghost** [krassowski/Anki-Night-Mode#36]
hi, great extension

if open anki -> open browser -> close browser - try to sync.
Anki crash 

https://ankiweb.net/shared/info/1496166067
on this url i found 2 coments related to "crash when  sync" 
probably they are having the same problem

if open anki -> open browser -> close browser - try to sync.
with the extension off "ctrl+n"
works perfectly

i'm using windows 7
Anki  2.0.51

**Comment by krassowski** [comment]
Thanks for letting me know. I am sorry to hear that the add-on causes this problem; I am aware that there are various issues with the add-on on Anki 2.0 as it uses outdated libraries which are prone to various imperfections in add-ons code and have bug themselves.

I've just tried to reproduce the issue (on Windows 8, unfortunately I do not have Windows 7 available) and the crash did not happen for me.

1. What version of the night mode add-on do you use (you can check from menubar: View→ Night Mode→ About)? 
2. Do you have any other add-on install which might be interfering with night-mode installed?
3. Do you know how to debug Python on Windows?
4. Have you tried using Anki 2.1?
5. Finally, do you have option "Enable in dialogs" checked in your menu? Does the crash still happen with this option turned on/off?

**Comment by Rickrr** [comment]
i turn off     "Enable in dialogs"    and it solved
now it's working perfectly, thanks.
