### ISSUE TITLE
CSS from .night_mode still applied if plugin set to deactivated

### ISSUE THREAD

**Issue by rathsky** [krassowski/Anki-Night-Mode#37]
Even when disabled entirely…

* both "enabled" options set to off
* reseted and nothing in "customize colors"
* everything in "choose what to style" disabled
 [but without deactivating the plugin itself – no other plugin present]

the plugin (2.1.6 on Anki 2.1.0b40, Linux) still applies everything in .card.night_mode CSS, if that's present.

**Comment by krassowski** [comment]
Thanks for the detailed report! I fixed this issue; will be included in the next release.

**Comment by rathsky** [comment]
The overall "Enable night mode" option now works "on/all off" as intended, but it's still applied to the cards when its enabled but styling of the cards themselves is not (related to #38).

(That is, I've got the three new commits applied, and in "Choose what to style" everything but "Anki Web View" and "Reviewer Cards" activated.)

**Comment by krassowski** [comment]
Well, that's because the `night_mode` class is supposed to be added when the night mode is enable, isn't it? ;)

I mean, the current behavior seems to be good for users who want to introduce their own styling of cards (they disabled "Anki Web View" and "Reviewer Cards", and want to add their own CSS for cards only).

Could provide an use-case in which we do want to have it selectively disabled?

**Comment by rathsky** [comment]
Basically, what I'd like is a way to use your plugin as a night theme for Anki that doesn't actually affect the way cards are rendered in any way – that is, a way to selectively disable night_mode only for the cards.

I probably misunderstood something here, but I thought this is functionality that "Anki Web View" resp. "Reviewer Cards" was meant to cover.

Actually I think it would be clearer if "Anki Web View" didn't affect card rendering at all so that this was entirely left to "Reviewer Cards" (maybe renamed as "Reviewer Web View" for consistency). Currently the former seems to be a subset of the latter, although I'm confused here as well, since with my settings they seem to cause exactly the same effect. (Also, I think "Editor Web View" should probably also cause the preview in the "Cards…" dialog to be affected.)

**Comment by krassowski** [comment]
> Basically, what I'd like is a way to use your plugin as a night theme for Anki that doesn't actually affect the way cards are rendered in any way – that is, a way to selectively disable night_mode only for the cards. (I guess you could however indeed make that the responsibility of the user, leaving it to them to remove any night_mode CSS instead if they so want).

Ok, so I think we have come to a mutual understanding now.

I will look into the idea of adding an option to disable the `night_mode` class later on:
I can imagine that someone got an Anki deck with pre-defined CSS styles which do not match their needs on PC, however, these work well for them on mobile. If the hypothetical user does not know CSS, it might be a good idea to let them disable this feature (as the styles defined for mobile might conflict with the PC needs and such users would not create their own styles anyway).

**Comment by krassowski** [comment]
@rathsky thank you again for your bug report and fruitful discussion.

I have just released a new version of Night Mode (2.1.7) which contains a patch for this bug. I will now close this issue, in favour of newly created #40, as the primary topic of this issue has been dealt with.

**Comment by rathsky** [comment]
Understood. Thank you for you work!
