### ISSUE TITLE
"Reviewer" option should only style the GUI parts

### ISSUE THREAD

**Issue by rathsky** [krassowski/Anki-Night-Mode#38]
Right now the "Reviewer" option in "choose what to style" will also cause the webview (ie. cards themselves) to be styled.

Pretty sure that's not what you intended as it's what the "Anki Web View" option seems for: That one doesn't seem to affect the GUI, and the latter has no separate option.

**Comment by krassowski** [comment]
Agreed, that is a bit counter-intuitive.

However some other styler than "Anki Web View" should take this responsibility: Anki web view is used in too many places (like deck browser, overview etc) and it would not be possible for me to test all the combinations. In fact, it is meant to only apply the styles in some rare states, when no other components could be easily monkeypatched and styled. Again, it is highly intertwined and enabling it the web view styling will make other options less useful.

**Comment by krassowski** [comment]
I developed a fix (see [this branch](https://github.com/krassowski/Anki-Night-Mode/tree/separate_web_view)) which adds "Reviewer Cards" styler which takes responsibility for the webview for reviewer only. It will allow you to style cards and other parts of the GUI separately.

I am going to release the fix on the weekend.

**Comment by krassowski** [comment]
Fix was included in the 2.1.7 release.
