### ISSUE TITLE
Copy & Paste Includes Span From Browse Screen

### ISSUE THREAD

**Issue by gr4nny** [krassowski/Anki-Night-Mode#4]
Sometimes I need to change cards from Front/Back to Cloze. If I am in night mode and copy and paste from browse to an add window, the <span color=... code is included. This results in the text color being permanently changed to the night mode color on the new card. 

As a work around, you can open HTML view and paste in there, which does not include the HTML code. This loses other format modifications like bold or underline. Ultimately, the best option is not to use night mode for this operation.

**Comment by krassowski** [comment]
I'm not sure if there is a much filed for improvement. I'll investigate it in February. Thanks for your report.

**Comment by gr4nny** [comment]
This also happens on the edit screen when cutting and pasting from one field to another.

**Comment by krassowski** [comment]
Fixed in Anki 2.1 beta 21: https://github.com/dae/anki/commit/4dbb87e4c192811122d1cab5d1cf849731c5780e
