### ISSUE TITLE
night_mode CSS not properly applied

### ISSUE THREAD

**Issue by rathsky** [krassowski/Anki-Night-Mode#41]
Currently I'm using Night Mode with the *Anki Web View* and *Reviewer Cards* stylers disabled.

Thus (afaik) no different styling other than a deck's .night_mode CSS should be applied, ie. the rendering ought almost entirely to match AnkiDroid's night mode.

1. That however only happens with the cards' back / answer sites. IOW, the front / question sites are left entirely as default, their night styling ignored.

2. If the two stylers get enabled, both front and back will be darkened, but rather than prioritizing a deck's own CSS for that, the plugin overrides its with its own. Minimal example CSS:

>.card.night_mode {
> color: #D74159;
> background-color: #181415;
>}

(No entry is present in "Customise colors")

**Comment by krassowski** [comment]
The point (1) is now fixed; the logic of a fancy transition effect (revealing the question by fade-in) introduced in one of the 2.1 betas was bluntly overwriting the card class. I implemented a workaround.

I see the point of (2) though it might be tricky - isn't the default style of every card type set to color: black, as an example of CSS usage? Anyway you could probably workaround this limitations using CSS `!important` directive, or we could try to find out a way to correct the add-on's styles so these have lower priority than `.card.night_mode` selector but higher than `.card`; not sure if it will be easy.
