### ISSUE TITLE
Some dialog text still black

### ISSUE THREAD

**Issue by rathsky** [krassowski/Anki-Night-Mode#44]
Some dialog text remains left black, making it rather hard to read with the box being colored black as well.

Eg. in the card browser:

- search & replace dialog (C-A-f)
- pure text dialog (C-S-x on a field) ([screenshot](https://i.imgur.com/ySBYlWj.png))

**Comment by krassowski** [comment]
Fixed, will look better in the next version. Thanks for taking your time to report this.
