### ISSUE TITLE
Tag menu text all black in Add card dialog box

### ISSUE THREAD

**Issue by anbu1538** [krassowski/Anki-Night-Mode#45]
While in the Add dialog box, the menu that comes up when typing in tags is all black and does not show what the tags are until I arrow over them. Anki version 2.0.52 and Night Mode version 1.2.3
Screenshot: 
![nightmode_tags](https://user-images.githubusercontent.com/29503563/45428920-3107fe80-b670-11e8-941a-b70ccb83e8dc.png)

**Comment by ganywa** [comment]
I experience this issue with Anki 2.1 and Night Mode 2.2.3 when using the addon TagEdit Subtag Completion.

**Comment by krassowski** [comment]
@ganywa I am afraid there is not much that I can do as this add-on creates a custom delegate object, using a part of the API which is not customizable with CSS styles (see https://github.com/glutanimate/anki-addons-misc/blob/master/src/tagedit_subtag_completer/tagedit_subtag_completer.py#L99).

If you want to have both add-ons, you might want to edit the color of the background.

To do so, use menu bar: Tools → Add-ons → select Night Mode → click on "View Files", find `stylers.py` file and replace `background-color` in completer to something lighter, e.g. gray or #d3d3d3:

https://github.com/krassowski/Anki-Night-Mode/blob/c7bdbf6bd0790de32c00c2d46c0922a734d191ae/night_mode/stylers.py#L680-L685

Remember to restart Anki to see the results!

**Comment by ganywa** [comment]
@krassowski Thanks; it solved the problem.

**Comment by Cardosaum** [comment]
@krassowski 

Thanks for showing where it's possible to change the color! was facing the same problem. Nigth-Mode is an excellent add-on, thank you for investing your time in creating it
