### ISSUE TITLE
Backspace becks not to previous line but to the beginning of first line

### ISSUE THREAD

**Issue by omega3** [krassowski/Anki-Night-Mode#48]
Unfortunately I discovered another bug that doesn't occur when Night Mode is disabled. 

In editor mode type something in the first line of text, press enter to start new line, type something, press enter. So you have now two lines of text and mouse pointer in third line. 

Press Backspace. Mouse pointer will go to the beginning of the first line in the field instead going to the end of previous line.

**Comment by krassowski** [comment]
It is only a consequence of the workaround I developed for #27 and which was improved in 2.2.1 and later in 2.2.2.

If you see any issues after updating to 2.2.2 (just released) please reopen this issue.

I hope that all the cases when the white background was being inserted are dealt with by now, but if you find any, please let me know (with the exact reproduction instructions, like these above or even better with some pictures).

**Comment by omega3** [comment]
I upgraded and seems to be ok. Although when I go to end of the line (end of sentence) and press delete, when there is a text in next line that is moved to the first line (where mouse pointer is, I mean to the end of sentence) for a short moment a white line appears and than a normal white text on dark background. But this is very fast and not a problem. 

Other than everything seems to be ok.
