### ISSUE TITLE
Expand use of .night_mode class to more parts of Anki's UI

### ISSUE THREAD

**Issue by glutanimate** [krassowski/Anki-Night-Mode#50]
Hi there!

Kudos first of all on all the recent improvements to Night Mode! It's nice to see development still being this active after all these years. Locale support looks great, and I would lie if I didn't say that this is something I'd love to add to my add-ons as well at some point.

Getting back to the issue at hand: I'm currently in the process of preparing the next release of [Review Heatmap](https://github.com/glutanimate/review-heatmap). One of the new features I would like to add is full support for Night Mode. I do have a [basic implementation working right now](https://github.com/glutanimate/review-heatmap/commit/3f51d9d3e6e38591df59f6f2c080b0329a9aefa2), but it's standing on rather shaky ground as reading mw.pm.profile really isn't sufficient to detect whether night mode is active or not.

My proposal with this feature request would be to also apply the `.night_mode` class to areas other than the Reviewer. For Review Heatmap specifically, it would be a great boon if I could write some Night Mode-specific CSS for the Deck Browser and Overview screens.

Thanks for giving this a read, and keep up the great work!

**Comment by krassowski** [comment]
Hi,

Thanks you, it's good to see your add-ons getting better and better too! When it comes to locale support, feel free to reuse the simplistic snippet from `languages.py` if it suits your needs.

I didn't realize (up until now) that the state stored in `mw.pm.profile` is a bit misleading - it was designed to provide a way of integration with other add-ons in mind initially, but I must have overlooked that when re-writing the add-on for 2.1 version and it had lost some of its functionality then. I think that your idea of using the `.night_mode` class is better for the web-based parts of the Anki interface. I will have to evaluate if it will be feasible for the Qt part too (as it uses some flavor of CSS, it may be the best solution as well). The advantage of the Night Mode applying classes itself is that the add-on offers ways of selectively disabling the dark styling in some screens/windows, and that would keep this functionality unaffected. 

I've just committed a first attempt to implement the `.night_mode` class in the Deck Browser and Overview screens. I did not test it thoroughly though as I do not have a development environment of Anki on my computer now and I am in a bit of a hurry. Please see if it works for you - I am specifically concerned whether the class is being deactivated after switching the night-mode off when on the Overview and Deck Browser screen. Hope it all works well for you.

Good luck!
