### ISSUE TITLE
Does not work with pop up dictionary add on

### ISSUE THREAD

**Issue by mynameisjohnz** [krassowski/Anki-Night-Mode#55]
#### Problem description

Hello this night mode is not compatible with the pop up dictionary add on. 
#### Checklist

*Please put x inside brackets if following sentences apply to you:*

 - [x] I verified that I use the lastest add-on version,
 - [x] I verified that I use the lastest Anki version,
 - [x] I tried to disable other add-ons to find the culprit,
 - [x] I checked if anyone reported this problem before, as well as Known issues section on add-ons page,
 - [ ] My issue is solved when holding shift while starting Anki.
 
#### Information about your Anki Setup

<details>

*Please open Anki, go to Help → About, look-up two lines, starting with `Version:` and `Qt` and copy-paste them below:*

```
Version:
Qt:
```

*Please got to Night Mode → About now and copy-paste the first line from the pop-up window below:*

```
Night Mode x.x.x
```

*Please fill in your OS details (Linux/Mac/Windows):*

```
OS:
```
 
 
*If you have a compatibility problem with a specific add-on or add-ons, please paste the add-on page links below:*
 - [Other add-on name](https://)
</details>

#### Backtrace (if any)

<details>

*If you had an error which resulted in producing exception with a backtrace, please paste the backtrace below:*

```python"
[paste your backtrace in here if you got any; otherwise feel free to remove this part]
```

</details>

**Comment by krassowski** [comment]
Hi there! It seems that you've missed #53 which is the most recent issue on the issue tracker. Closing as a duplicate. If your problem is not addressed in #53, please feel free to reopen.
