### ISSUE TITLE
Compatability with Right Hand Review 2.1 (jkl;)

### ISSUE THREAD

**Issue by alaskakw** [krassowski/Anki-Night-Mode#58]
#### Problem description
When using Right Hand Revies on anki 2.1 (addon code: 1212877655) the reviewer is not in night mode. After looking at the code it seems Right Hand Reviews replaces the reviewer with a hard-coded version. My first thought on how to solve this would be to find the code in Night Mode that colors the reviewer and paste it into my Right Hand Reviews code. Does that sound feasible?

![image](https://user-images.githubusercontent.com/29007905/51088397-e11b7000-1713-11e9-9946-aeffbe195c6c.png)

#### Checklist

*Please put x inside brackets if following sentences apply to you:*

 - [x ] I verified that I use the lastest add-on version,
 - [x ] I verified that I use the lastest Anki version,
 - [x ] I tried to disable other add-ons to find the culprit,
 - [x ] I checked if anyone reported this problem before, as well as Known issues section on add-ons page,
 - [x ] My issue is solved when holding shift while starting Anki. (it's solved when I disable either of the conflicting addons)
 
#### Information about your Anki Setup

<details>

*Please open Anki, go to Help → About, look-up two lines, starting with `Version:` and `Qt` and copy-paste them below:*

```
Version: 2.1.7
Qt:5.12.0 PyQt 5.11.3
```

*Please got to Night Mode → About now and copy-paste the first line from the pop-up window below:*

```
Night Mode 2.2.3
```

*Please fill in your OS details (Linux/Mac/Windows):*

```
OS: Windows 10
```
 
 
*If you have a compatibility problem with a specific add-on or add-ons, please paste the add-on page links below:*
 - [Right Hand Reviews (jkl;)](https://ankiweb.net/shared/info/1212877655)
</details>

#### Backtrace (if any)

<details>

*If you had an error which resulted in producing exception with a backtrace, please paste the backtrace below:*

```python"
[paste your backtrace in here if you got any; otherwise feel free to remove this part]
```

</details>

**Comment by krassowski** [comment]
Hi @alaskakw, thank you for letting me know (and exemplary issue filing) - I will try to look into this within a week. Have a good day!

**Comment by krassowski** [comment]
> My first thought on how to solve this would be to find the code in Night Mode that colors the reviewer and paste it into my Right Hand Reviews code. Does that sound feasible?

Actually, there is a better solution - the addon could use `wrap()` utility (designed for extending Anki, see [Monkey Patching and Method Wrapping](https://apps.ankiweb.net/docs/addons.html#monkey-patching-and-method-wrapping)) instead of inheritance. CC @AustinHasten

**Comment by krassowski** [comment]
Cross-referencing: https://github.com/AustinHasten/AnkiRightHandReviews/issues/1

**Comment by krassowski** [comment]
Closing, as it was fixed in the other add-on and confirmed by @alaskakw to work in the linked issue.
