### ISSUE TITLE
conditional text color change [feature request]

### ISSUE THREAD

**Issue by omega3** [krassowski/Anki-Night-Mode#6]
Look at difference
colour #000080
http://imgur.com/a/n3paa

So far I have used day mode. When I turned to night mode it appeared that some text colours looks bad. It is not default colour but just colouring of selected text. I think changing this in the whole deck would require exporting a deck to text and search and replace colour values.  I would prefer not to do that. Editing single cards is even a bigger pain.
Would be possible to add possibility to edit this-add on and personalize so that user can choose that this specified text colour (for example #000080) must be change to another specified by user colour  (for example #EB7331) when night mode is used?

**Comment by krassowski** [comment]
Yes there is an option for this to be implemented. Since the default coloring in Anki is done be adding font tag like this: `<font color="#7d7d7d">grey text</font>`, we just need to generate a set of custom CSS selectors matching the target color. But it won't work for some edge-cases like colored text pasted from elsewhere (where the color might be applied with complicated style attribute, not with use of `<font>` element). Is that a good solution for you?

**Comment by omega3** [comment]
Yes. It is good for me. Actually I use Anki option "Strip HTML when pasting text". I think you can even add in description that this enhancement will work only when this option is active.

Just a note to be sure that I am understood correctly: requesting this enhancement I am taking about parts of text that I previously coloured with Anki options F7 and F8 (not the default (white) font colour or anything set in card templates).

**Comment by omega3** [comment]
Anki uses this system of colour #ff0000 when option F7, F8 is used. Is it possible to replace **permanently** in html code only this values without changing anything else (hexadecimal to decimal or to text)? If yes I would do it once and not need changes in night mode (although other users might still benefit from such enhancement). This would be more simple solution than changing add-on.
And perhaps this add-on could be useful
https://ankiweb.net/shared/info/1114708966
Discussion
https://anki.tenderapp.com/discussions/add-ons/7526-clear-field-formatting-html-in-bulk-needs-improvement

If not I can do it outside of Anki in text editor.

**Comment by omega3** [comment]
The problem is sorted out in another way. I used this add-on 
~ Clear Field Formatting HTML
https://ankiweb.net/shared/info/1114708966

**Comment by krassowski** [comment]
I added an option to replace colors by specifying dictionary entries with mappings. I think that it is a useful option and it should be included in graphical interface in the future. PRs are welcome.
