### ISSUE TITLE
Change background color

### ISSUE THREAD

**Issue by Gueazy** [krassowski/Anki-Night-Mode#61]
Hello, can I change the background color of my cards in the settings ?
Thx

**Comment by krassowski** [comment]
You can change the background of everything at once in the settings (View → Night Mode → Change background color) OR change the background for specific card types using CSS. In short, you would need to open the card edition window, click on "Cards", and in the window modify "Styling" to include:

```
.night_mode *{
    background: red;
}
```

You can also define custom wrappers for content on the cards to style them selectively, like this:
![screenshot from 2018-10-21 14-08-55](https://user-images.githubusercontent.com/5832902/47267375-f16be680-d53a-11e8-8a93-a757bb3d7166.png)

Related to #52.
