### ISSUE TITLE
White rectangle around buttons in editor.

### ISSUE THREAD

**Issue by mjuzikfrik** [krassowski/Anki-Night-Mode#65]
When in night mode I get a white rectangle around button in the both in th editor and in the browser.

 - [x] I verified that I use the lastest add-on version,
 - [x] I verified that I use the lastest Anki version,
 - [x] I tried to disable other add-ons to find the culprit,
 - [x] I checked if anyone reported this problem before, as well as Known issues section on add-ons page,
 - [ ] My issue is solved when holding shift while starting Anki.
 
```
Version 2.1.11 (3cf770c7)
Qt 5.12.1 PyQt 5.11.3
```
```
Night Mode 2.2.3
```
```
OS: Windows 10 1809 x64 
```

![Screenshot_1](https://user-images.githubusercontent.com/16630872/54379811-68d91880-468a-11e9-9681-73cea7dfb0fc.png)

**Comment by krassowski** [comment]
Thank you for your report. This was a result of [a change in Anki 2.1.8](https://github.com/dae/anki/commit/f91e30a2c1fdc9c539ec1f6d37157cdb489dbe82) and I just addressed it in 206112e.

I will be releasing a new version of the add-on this weekend.
