### ISSUE TITLE
Anki hangs on opening 'Night Mode' menu

### ISSUE THREAD

**Issue by omega3** [krassowski/Anki-Night-Mode#7]
Witam
Niestety google twierdzi, że Pana mail na gazecie jest "rejected by the server for the recipient domain", dlatego piszę tu.

Miałem aktywną opcję night mode. Zmieniałem kolor tekstu za pomocą standardowych opcji Anki. Potem nacisnąłem na menu żeby wejść w opcje night mode. W tym momencie Anki zawiesiła się. Musiałem kill process. :) W załączeniu raport.

To może nie ma bezpośredniego związku z Pana wtyczką, gdyż Anki zawieszała się lub całkiem wywalało program nawet kiedy nie używałem tej wtyczki. Ale wyczytałem, że używa Pan Ubuntu, więc może będzie w stanie Pan pomóc i potwierdzić zgłoszony na launchpad bug.
Twórcy Anki uważają, że to nie ma nic wspólnego z kodem Anki. Może i tak. Chodzi o to żeby ktoś po stronie ubuntu się tym zajął.

Założyłem tematy
Anki keeps crashing on Kubuntu 16.04
https://anki.tenderapp.com/discussions/ankidesktop/18360-anki-keeps-crashing-on-kubuntu-1604
https://bugs.launchpad.net/ubuntu/+source/qt4-x11/+bug/1495274

Teraz podejrzewam, że może źle wskazałem paczkę na launchpad i że chyba chodzi o python-qt4. Ale jak ktoś potwierdzi bug to można będzie poprawić w komentarzu albo po zobaczeniu crash raport sami poprawią. Bez potwierdzenia przez kolejną osobę, developerzy Ubuntu nawet się nie zainteresują tym.

Niestety na forum anki nie można się skontaktować z innymi użytkownikami, którzy zgłaszali problem. Można tylko czekać aż zauważą kolejny temat.

Problem nie występuje od razu. Czasem trzeba zrobić kilka operacji, zrobić trochę powtórek, edycji, wybrać jakieś kolory, przejść w tryb nauki i dopiero potem Anki się wiesza. Może to ma coś wspólnego z pamięcią. 

Raport:

```
gdb
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
(gdb) file python
Reading symbols from python...(no debugging symbols found)...done.
(gdb) run /usr/bin/anki
Starting program: /usr/bin/python /usr/bin/anki
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe1278700 (LWP 4991)]
[New Thread 0x7fff9cc34700 (LWP 4992)]
[New Thread 0x7fff97c5b700 (LWP 4993)]
[New Thread 0x7fff9679d700 (LWP 4996)]
[Thread 0x7fff97c5b700 (LWP 4993) exited]
[New Thread 0x7fff97c5b700 (LWP 4997)]

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff3b0c409 in ?? () from /usr/lib/python2.7/dist-packages/PyQt4/QtCore.so
(gdb) bt
#0  0x00007ffff3b0c409 in ?? () from /usr/lib/python2.7/dist-packages/PyQt4/QtCore.so
#1  0x00007ffff3604e09 in QMetaObject::cast(QObject*) const () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#2  0x00007ffff1d9efe8 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#3  0x00007ffff1da1286 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#4  0x00007ffff1db0446 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#5  0x00007ffff1aca77f in QWidgetPrivate::setStyle_helper(QStyle*, bool, bool) ()
   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#6  0x00007ffff1acaadc in QWidgetPrivate::inheritStyle() () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#7  0x00007ffff1aca7ce in QWidgetPrivate::setStyle_helper(QStyle*, bool, bool) ()
   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#8  0x00007ffff1acaadc in QWidgetPrivate::inheritStyle() () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#9  0x00007ffff2a864c2 in ?? () from /usr/lib/python2.7/dist-packages/PyQt4/QtGui.so
#10 0x000000000049968d in PyEval_EvalFrameEx ()
#11 0x00000000004a090c in PyEval_EvalCodeEx ()
#12 0x0000000000499a52 in PyEval_EvalFrameEx ()
#13 0x0000000000499ef2 in PyEval_EvalFrameEx ()
#14 0x00000000004a1c9a in ?? ()
#15 0x00000000004dc9cb in PyEval_CallObjectWithKeywords ()
#16 0x00007ffff603a048 in sip_api_invoke_slot () from /usr/lib/python2.7/dist-packages/sip.so
#17 0x00007ffff3b08a26 in ?? () from /usr/lib/python2.7/dist-packages/PyQt4/QtCore.so
#18 0x00007ffff3b08d40 in ?? () from /usr/lib/python2.7/dist-packages/PyQt4/QtCore.so
#19 0x00007ffff3b098dd in ?? () from /usr/lib/python2.7/dist-packages/PyQt4/QtCore.so
#20 0x00007ffff3612a78 in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) ()
   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#21 0x00007ffff1a7fa62 in QAction::triggered(bool) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#22 0x00007ffff1a81433 in QAction::activate(QAction::ActionEvent) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#23 0x00007ffff1eaf509 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#24 0x00007ffff1eb3a39 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#25 0x00007ffff2926abb in ?? () from /usr/lib/python2.7/dist-packages/PyQt4/QtGui.so
#26 0x00007ffff1ad551a in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#27 0x00007ffff1eb783b in QMenu::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#28 0x00007ffff2925a2b in ?? () from /usr/lib/python2.7/dist-packages/PyQt4/QtGui.so
#29 0x00007ffff1a85e2c in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#30 0x00007ffff1a8c5dd in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#31 0x00007ffff2ab0186 in ?? () from /usr/lib/python2.7/dist-packages/PyQt4/QtGui.so
#32 0x00007ffff35fe4dd in QCoreApplication::notifyInternal(QObject*, QEvent*) ()
---Type <return> to continue, or q <return> to quit---
```

**Comment by krassowski** [comment]
Thank you for Your report. The trackback you posted was a thing I was looking for a some time ago.

I don't have any idea what has caused the bug. Help from anybody with more experience with PyQt4 will be highly appreciated. I have experienced different issues with Qt4 on my own and as you wrote they occur without the add-on too, but from reports and personal experience I guess some code in add-on promotes those bugs to happen more often.

What options did you have checked in the menu when the crash happened?

Ps. Writing in English may allow engaging more users to help in resolving the issue. If you could edit you message it would be great :) Pozdrawiam.

**Comment by omega3** [comment]
I just clicked on menu "view" and that's it. It hanged. So I needed to terminate. 
But it doesn’t happen every time so it is difficult to track. It also happens when I use Anki option for changing colour F8. 
Damien wrote that we need to wait until he upgrades Anki to qt5

"Anki is currently stuck on Qt4 because other issues were found in Qt5 that prevented Anki from moving to it. I'm afraid it's not helpful to report issues to the Qt folks, as Anki is not on the latest library version and they expect an isolated test case instead of just being told an app running on their toolkit is breaking. Until I can get Anki running on a newer toolkit version, unless you are a developer who can narrow this down to a specific test case I'm afraid your best bet is to run Anki in wine or a virtual machine instead."

> Ps. Writing in English may allow engaging more users to help in resolving the issue. If you could edit you message it would be great :)
Yes, I know, but it is the same that I wrote on Anki forum and I have here a link.

**Comment by krassowski** [comment]
Ok, thank you. I will go back to the topic soon but now I have another tasks scheduled. As for summary and reference for anyone who would like to debug those crashes: It happens mostly on Linux systems, suspected actions are: clicking edit button, editing colors, or switch to night mode. There are some sources reporting how to take care of the problematic PyQt4:
http://stackoverflow.com/questions/11945183/what-are-good-practices-for-avoiding-crashes-hangs-in-pyqt
http://enki-editor.org/2014/08/23/Pyqt_mem_mgmt.html
PRs are welcome.

**Comment by krassowski** [comment]
After reading more threads on Anki forum all I can say is that it is not specific to Night-Mode and that the crashes in Anki 2.0 are indeed caused by various bugs in PyQT4. As PyQt4 is not supported for a long time and this addon has now a fully working version for Anki 2.1 (which uses PyQT5) I am going to close this issue for now.
