### ISSUE TITLE
add hook for other add-ons

### ISSUE THREAD

**Issue by ijgnd** [krassowski/Anki-Night-Mode#77]
First of all: Thanks for creating this fantastic add-on.

Some add-ons are not affected by the night mode like [Extended Card Stats During Review](https://ankiweb.net/shared/info/1008566916) or [Syllabus - Anki Statistics and Export by Tag and Deck](https://ankiweb.net/shared/info/668156440). 

A `runHook` would help future add-on authors to change their add-ons when user activates the night mode. You already added a hook for the old 2.0 version for lovac42, see https://github.com/krassowski/Anki-Night-Mode/pull/51 . Such a function for the current branch for 2.1 would be very useful.

At the moment I use `__import__("1496166067").night_mode.config.state_on.value` in my version of the "Card Stats Sidebar" add-on which is much more complicated. I would very much prefer to just use "addHook" for my add-on [extended (table) editor](https://ankiweb.net/shared/info/805891399) and [extended html editor](https://ankiweb.net/shared/info/1043915942) than figuring out how to solely rely on css.

Thanks

**Comment by krassowski** [comment]
I agree that this should be addressed and would be happy to accept pull requests!

**Comment by ijgnd** [comment]
Many thanks @lovac42 for the pull request and thanks @krassowski for quickly merging it.
