### ISSUE TITLE
Freeze in night mode

### ISSUE THREAD

**Issue by nueij** [krassowski/Anki-Night-Mode#79]
#### Problem description
Hello,

When I open Anki, it starts in night mode and freezes when I try to change out of night mode. It also freezes when I try to open preferences. The problem goes away when I uninstall the night mode add-on and doesn't go away when I reinstalled. 

I can't think of any precipitating factors for this issue; I closed my laptop (in sleep) when it was working fine and opened it up again to have this issue.

Please help thank you!

#### Checklist

*Please put x inside brackets if following sentences apply to you:*

 - [X] I verified that I use the lastest add-on version,
 - [ ] I verified that I use the lastest Anki version
 - [X] I tried to disable other add-ons to find the culprit,
 - [X] I checked if anyone reported this problem before, as well as Known issues section on add-ons page,
 - [X] My issue is solved when holding shift while starting Anki.
 
#### Information about your Anki Setup

<details>

*Please open Anki, go to Help → About, look-up two lines, starting with `Version:` and `Qt` and copy-paste them below:*

```
Version 2.0.52
Qt 4.8.4 PyQt 4.10
```

*Please got to Night Mode → About now and copy-paste the first line from the pop-up window below:*

```
Can't find this information; in the night mode options I only have edit and delete
Night Mode x.x.x
```

*Please fill in your OS details (Linux/Mac/Windows):*

```
OS: Windows 10 Pro
```
 
 
*If you have a compatibility problem with a specific add-on or add-ons, please paste the add-on page links below:*
 - [Other add-on name](https://)
</details>

#### Backtrace (if any)

<details>

*If you had an error which resulted in producing exception with a backtrace, please paste the backtrace below:*

```python"
[paste your backtrace in here if you got any; otherwise feel free to remove this part]
```

</details>

**Comment by krassowski** [comment]
Thank you for the report. I understand the nuisance; It seems that you use an old Anki version. There is a newer Anki version 2.1 for which this add-on was completely rewritten and includes many more functionalities.

Unfortunately, I cannot support the old Anki version as it is based on Qt 4 which has a lot of issues, some of which may cause crashes. I would not feel safe using Qt4 any longer - it does not even receive security patches. It was originally released 15 years ago and the last release was in 2011 - 8 years ago (see https://en.wikipedia.org/wiki/Qt_version_history). The new version uses Qt5 which is more up to today's stability standards (unless you use Mac, there are known problems with Mac, reagrless of Qt version).

**Comment by krassowski** [comment]
Please feel free to re-open if you experience such an issue in the new version (which is unlikely, but possible).
