### ISSUE TITLE
Night mode also in editor background

### ISSUE THREAD

**Issue by omega3** [krassowski/Anki-Night-Mode#8]
Can you please do night mode in edit mode - text fields. It is still white background. Not very convenient when someone uses bright colours for night mode like yellow or other. There are almost invisible in editor. I would like to have a full night mode experience. :)
In card template it is night mode and I am glad of that. There is no reason to leave editor background white.

**Comment by krassowski** [comment]
Could you post a screenshot of the exact place where you need updated colors?

**Comment by omega3** [comment]
Sorry for that. In is invalid request. I have just found: "Enable in dialogues"
