### ISSUE TITLE
Latest release of Night Mode doesn't work when turned off in dialogs (to prevent small sidebar issue)

### ISSUE THREAD

**Issue by AnKingMed** [krassowski/Anki-Night-Mode#97]
#### Problem description

I have the small sidebar issue so I typically use nightmode with "enable in dialogs" turned off and I uncheck "browser" and "browser package" to make it look more normal. The latest release makes it so the sidebar is totally whited out when using better tags and also alters the color formatting on other add-ons (i.e. extended tag add edit)

#### Checklist

*Please put x inside brackets if following sentences apply to you:*

 - [x ] I verified that I use the lastest add-on version,
 - [x] I verified that I use the lastest Anki version,
 - [x] I tried to disable other add-ons to find the culprit,
 - [x] I checked if anyone reported this problem before, as well as Known issues section on add-ons page,
 - [ ] My issue is solved when holding shift while starting Anki.
 
#### Information about your Anki Setup

<details>

*Please open Anki, go to Help → About, look-up two lines, starting with `Version:` and `Qt` and copy-paste them below:*
Version 2.1.19 (3c8690ae)
Python 3.8.0 Qt 5.14.0 PyQt 5.13.2

*Please got to Night Mode → About now and copy-paste the first line from the pop-up window below:*

```
Night Mode 2.3.1
```

*Please fill in your OS details (Linux/Mac/Windows):*

```
OS: Mac OS Catalina
```
 
 
*If you have a compatibility problem with a specific add-on or add-ons, please paste the add-on page links below:*
 - [Extended Tag Add Edit dialog](https://ankiweb.net/shared/info/1135507717)
- Bettertags (only available through patreon)
some of the colors on this are off and the sidebar does not show the tag icons.  Everything was normal prior to the 2.3.0 release (I'm on 2.2.4 and it works fine)
![1946312c-9b0d-43ac-963f-39fdd195505e](https://user-images.githubusercontent.com/57678116/72767487-533d5500-3bb1-11ea-84b7-5938519b4724.jpg)

#### Backtrace (if any)

<details>

*If you had an error which resulted in producing exception with a backtrace, please paste the backtrace below:*

```python"
[paste your backtrace in here if you got any; otherwise feel free to remove this part]
```

</details>

**Comment by lovac42** [comment]
![image](https://user-images.githubusercontent.com/42665127/72782897-00848d00-3bf3-11ea-96bc-51b104200ee9.png)

**Comment by AnKingMed** [comment]
Thanks! I missed that
