### ISSUE TITLE
changing a profile raises "Exception: Action enable_night_mode already exists"

### ISSUE THREAD

**Issue by ijgnd** [krassowski/Anki-Night-Mode#98]
With Night Mode 2.3.1 (according to View->Night Mode->About) in Anki 2.1.19 and 2.1.20 beta2 on Linux after changing a profile I get an error: `Action enable_night_mode already exists`. The whole backtrace is below at [1]. The Checklist from your issue template is at [2]. As far as I see this error was introduced with @lovac42's commit 0bb1032. This should be fixed by minimally changing `__init__.py`, e.g. to something like in [3]. So far I have seen no side-effects of this change.

[1] backlist

```python
Anki 2.1.20 (c9a46268) Python 3.8.1 Qt 5.14.0 PyQt 5.13.2
Platform: Linux
Flags: frz=True ao=True sv=1
Add-ons possibly involved: 1496166067

Caught exception:
Traceback (most recent call last):
  File "aqt/progress.py", line 73, in handler
  File ".../addons21/1496166067/__init__.py", line 11, in delayedLoader
    night_mode = NightMode()
  File ".../addons21/1496166067/night_mode.py", line 131, in __init__
    self.menu = Menu(
  File ".../addons21/1496166067/menu.py", line 55, in __init__
    self.create_action(
  File ".../addons21/1496166067/menu.py", line 75, in create_action
    raise Exception(message)
Exception: Action enable_night_mode already exists
```

---

[2] Checklist

 - [x] I verified that I use the lastest add-on version,
 - [x] I verified that I use the lastest Anki version,
 - [x] I tried to disable other add-ons to find the culprit,
 - [x] I checked if anyone reported this problem before, as well as Known issues section on add-ons page,
 - [x] My issue is solved when holding shift while starting Anki.
 
----

[3]

change 
```python
def delayedLoader():
    from .night_mode import NightMode
    night_mode = NightMode()
    night_mode.load()
```
to 
```python
nm = None
def delayedLoader():
    global nm
    if not nm:
        from .night_mode import NightMode
        nm = NightMode()
        nm.load()
```

**Comment by lovac42** [comment]
Thanks ijgnd. I made the PR. You are more than capable of making the PR too. Don't be shy.

**Comment by ijgnd** [comment]
Thanks @lovac42 for the quick fix and encouragement.
